{% set data = load_setup_py_data() %}

package:
  name: openalea.dss
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} setup.py install 

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
  run:
    - python >=3.6
    - agroservices 
    - weatherdata
    - matplotlib
  
test:
  requires:
    - pytest
  imports:
    - weatherdata
  source_files:
    - test/**
  #commands:
  #  - cd test
  #  - pytest -v --ignore=test_weatherdata.py
about:
  home: {{ data.get('url') }}
  license: GPL-v3
  summary: {{ data.get('description') }}

