name: DSS
channels:
  - conda-forge
  - openalea3

dependencies:
 - python=3.8
 - openalea.deploy
 - requests (agroservices) 
 - appdirs (agroservices)
 - bs4 (agroservices)
 - colorlog (agroservices)
 - requests_cache (agroservices)
 - xarray (weatherdata)
 - pandas
 - pytest
 - sphinx_rtd_theme
 - nbsphinx
 - nbsphinx-link
 - pip:
  - agroservices
  - weatherdata