# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-05-26T13:26:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ConfigParameters(BaseModel):
    timeZone: str
    timeStart: str
    timeEnd: str


class LocationWeatherDatum(BaseModel):
    longitude: float
    latitude: float
    altitude: float
    data: List[List[float]]
    length: int
    width: int


class WeatherData(BaseModel):
    timeStart: str
    timeEnd: str
    interval: int
    weatherParameters: List[int]
    locationWeatherData: List[LocationWeatherDatum]


class Model(BaseModel):
    modelId: str
    configParameters: ConfigParameters
    weatherData: WeatherData
